NUM_OF_IMAGES_PER_LINE = 10
IMAGE_HEIGHT = 50  # pixels
IMAGE_WIDTH = 50  # pixels
LINE_HEIGHT_PIXEL = 2
NUM_OF_LINES = NUM_OF_IMAGES_PER_LINE + 1
NUM_OF_PLANES = 4

WINDOW_HEIGHT = (IMAGE_HEIGHT * NUM_OF_IMAGES_PER_LINE) + (LINE_HEIGHT_PIXEL * NUM_OF_LINES)
WINDOW_WIDTH = (IMAGE_WIDTH * NUM_OF_IMAGES_PER_LINE) + (LINE_HEIGHT_PIXEL * NUM_OF_LINES)

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
